### ISSUE TITLE
Link's color based on status not percentage

### ISSUE THREAD

**Issue by VictorJ76** [exoscale/php-weathermap-obselete#3]
Hello, 

I would like to control the colour of the link, actually they change with percentage bandwidth and I want my links be green when the port is Up and red when my port is Down. 
I found someone who share this , but no success for me. 
```
SCALE ifstatus 0 1.5 255 0 0
SCALE ifstatus 1.5 2.5 0 255 0 
```
http://forums.cacti.net/viewtopic.php?f=16&t=30563

**Comment by vincentbernat** [comment]
The real home for Network Weathermap is https://github.com/howardjones/network-weathermap. We are just users of it and this repository is out-of-date. I think it was setup before the original software was present on GitHub. We'll close it shortly to avoid confusion.

**Comment by VictorJ76** [comment]
Okok thank you for replying. 

best regards
